name: Test node app
on: [push]
jobs: 
  print: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print to console
        run: |
          echo "Hello world"
          echo "2 line print"
      - name: get repisitory code
          uses: actions/checkout@v3
        
