name: React app test
on: 
  push:
    branches:
      - main
    path-ignore:
      # - ' .github/workflows/*'
env:
  name: goupriver
  # gh-secrets: ${{secrets.SSH-KEY}}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: string
        run: | 
          echo "${{ toJSON(github) }}"
          echo "${{ env.name }}"
      # - name: copy repo
      #   uses: actions/checkout@v3
      # - name: i deps
      #   run: npm ci
      # - name: run test
      #   run: npm run test
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: print
  #       run: |
  #         echo hello world!

