name: React app test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: string
        run: echo "${{toJSON(github)}}"
      # - name: copy repo
      #   uses: actions/checkout@v3
      # - name: i deps
      #   run: npm ci
      # - name: run test
      #   run: npm run test
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: print
  #       run: |
  #         echo hello world!

